language: go
go:
- '1.10'
sudo: required
services:
- docker
script:
- make build
deploy:
- provider: script
  script: make push
  skip_cleanup: true
  on:
    tags: true
- provider: script
  script: DOCKER_PASSWORD="$DOCKER_HUB_PASSWORD" DOCKER_USERNAME=nvogel DOCKER_REGISTRY=registry.hub.docker.com NS=nvogel make push
  skip_cleanup: true
  on:
    tags: true
env:
  global:
  - secure: LaZAdfwigknohkrBf1T0J2HtoOGhsKs0Almf1imr1q6ilBOySgXCKTxFBOP1W+vyMptoHCBL5eUldJWy8odVdjwZSJCdy8dUYrhZY8VYdQ6TE16lUAUHgAA1Plcf8VY7FV9IpQ3rZbdBDii3S6tADA1XtzTfh4GDU06Zt8qBb9L8uluCWnzEoeJjLejgBD/efxfMiJP0hecKPogE92NTXHXaQebRl+C90qMqOBtNflDoQip4q2nqQiQLt/zQVxaWANipH5nP8/LBH5mPESRSBrPdI4aSZNtcbcRl3W7/CNBXGq6/z/JUhud9OjGRdELr92MVUvgOl00RQNk316deLMxWHcidglWgejK/0jcjeRzK2EZyLwpV2GS9lnb+JF2nuvhOWAxHYU4pBcMZB5/JB7VzFu6Px8DmuS3sfJC2Oz+zVCObU5OEzE2tgGC2ShBeACaArLpc6noeBBpequwfiJfnsPf/+8bsjHrQ5tI2uJEITtwByrEsetjDT2/VByWveof8bYuhC0JwO6KcKfmbKWXfOJLWAlYgG5nQ+lE/F0Usvz8RwDRxjlBow3KhvDRKd/NiYe+dckp8MxFYOKrxlU82zmSlJZdcKu37jT/R+mBiPEWr39nNDvJ053MYjDcEBsvqvVOha4DwUoEv3Xz4k/TM/yrojIACVccbls8MhTk=
  - secure: TrKsazMtkhJGtKYT3LdkVzGsnshsPMHGcT2gnS27f/N9qjel03DJ0M5VxETsDp17EuG7hlzxa2Ex9IR2wiaoWvRCCOjSP3XoTWQYLUy8LzMJfdL/0118EMlnuuUpMXxS8Lx8xVImA/+EZzZioUaVur29Ub2bAFEhzo2B3FwDnA73t+B2TEASL8V9Teic1BVJhGJN14Pys79J1XTfHXgdT0AplpDgDC+491fpy0cl4lDH+EJpef/xE38goB9eFOCEvcXEpLBWblQ4jyHb1xIQecr9Sd7eeVc/Fvc95tRHY7fIJ4472sJAbQvw36PZPRo6lrNezudtifV0BpWan4qi+1c97xkE9878oB5zKrrr2IT8rwP1W+N23vv67tELBY2U1kDO+5Q7mSlP297OGFSy0De7WK60bpRbuG2jlcrEkKI6GNOH9sX0DQaOTiQewUvXS+isJdXjnRkMLN8QvA5KZD3BCI7qrahS7etTjvvo9dNVtZznFB0h+Sy0UK2zRUzbTRjxGIuQ59sz/XtpHBfJOXWlv7Pf1x9xFBnIl5jlKGu/xTd5dqro72N7+4fbqifbZx0G24JvmsUjnC5yZvuf1jRSnRqtaJzYqSILmjvRGc38Q3yNDaJm535o8S62/KncaYG3Zil9P2Eb5x/jObJjnxUG0cAlCVGWYXeifCJSS5o=
